language: python
python:
- '2.7'

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git v2018.3.3

install:
  - sudo mkdir -p /srv/salt/states
  - sudo cp -r . /srv/salt/states
  - sudo cp .travis/minion /etc/salt/minion
  - sudo cp .travis/top.sls /srv/salt/states
  - sudo service salt-minion restart

  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_highstate -l debug  --local --retcode-passthrough
